unbind r        
bind r source-file ~/.tmux.conf
set -g prefix C-a
set -g mouse on
set-option -g focus-events on
set -g history-limit 100000
set-option -g renumber-windows on
set-option -g set-titles on

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind = select-layout even-horizontal
bind | select-layout even-vertical

bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# status bar
set -g base-index 1
set -g status-position bottom
set -g status-left ' #[fg=white]#S'
set -g status-right '#[fg=white]%d-%m-%y %H:%M '
set -g status-style 'bg=default'
set -g status-justify absolute-centre
setw -g window-status-current-style 'fg=black bg=blue'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-style 'fg=red'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @vim_navigator_mapping_left "C-h"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_right "C-l"
set -g @vim_navigator_mapping_prev ""

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
